package com.example.studentapi.controller;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for StudentController
 * Generated by IBM Bob - Assignment Decoder
 * Target: 80%+ code coverage
 */
@WebMvcTest(StudentController.class)
@DisplayName("Student Controller Tests")
class StudentControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private StudentService studentService;

    @Test
    @DisplayName("GET /api/students should return all students")
    void testGetAllStudents() throws Exception {
        // Given
        List<Student> students = Arrays.asList(
            new Student(1L, "John Doe", "john@example.com", 20),
            new Student(2L, "Jane Smith", "jane@example.com", 22)
        );
        when(studentService.findAll()).thenReturn(students);

        // When & Then
        mockMvc.perform(get("/api/students"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.length()").value(2))
            .andExpect(jsonPath("$[0].name").value("John Doe"));
    }

    @Test
    @DisplayName("GET /api/students/{id} should return student when found")
    void testGetStudentById_Found() throws Exception {
        // Given
        Student student = new Student(1L, "John Doe", "john@example.com", 20);
        when(studentService.findById(1L)).thenReturn(student);

        // When & Then
        mockMvc.perform(get("/api/students/1"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.name").value("John Doe"))
            .andExpect(jsonPath("$.email").value("john@example.com"));
    }

    @Test
    @DisplayName("POST /api/students should create student with valid data")
    void testCreateStudent_ValidData() throws Exception {
        // Given
        String studentJson = "{\"name\":\"John Doe\",\"email\":\"john@example.com\",\"age\":20}";
        Student created = new Student(1L, "John Doe", "john@example.com", 20);
        when(studentService.save(any(Student.class))).thenReturn(created);

        // When & Then
        mockMvc.perform(post("/api/students")
                .contentType(MediaType.APPLICATION_JSON)
                .content(studentJson))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.id").value(1))
            .andExpect(jsonPath("$.name").value("John Doe"));
    }

    @Test
    @DisplayName("POST /api/students should reject invalid email")
    void testCreateStudent_InvalidEmail() throws Exception {
        // Given
        String studentJson = "{\"name\":\"John Doe\",\"email\":\"invalid-email\",\"age\":20}";

        // When & Then
        mockMvc.perform(post("/api/students")
                .contentType(MediaType.APPLICATION_JSON)
                .content(studentJson))
            .andExpect(status().isBadRequest());
    }

    @Test
    @DisplayName("POST /api/students should reject age below 18")
    void testCreateStudent_AgeTooYoung() throws Exception {
        // Given
        String studentJson = "{\"name\":\"John Doe\",\"email\":\"john@example.com\",\"age\":17}";

        // When & Then
        mockMvc.perform(post("/api/students")
                .contentType(MediaType.APPLICATION_JSON)
                .content(studentJson))
            .andExpect(status().isBadRequest());
    }

    @Test
    @DisplayName("PUT /api/students/{id} should update existing student")
    void testUpdateStudent() throws Exception {
        // Given
        String studentJson = "{\"name\":\"John Updated\",\"email\":\"john@example.com\",\"age\":21}";
        Student updated = new Student(1L, "John Updated", "john@example.com", 21);
        when(studentService.update(any(Student.class))).thenReturn(updated);

        // When & Then
        mockMvc.perform(put("/api/students/1")
                .contentType(MediaType.APPLICATION_JSON)
                .content(studentJson))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.name").value("John Updated"));
    }

    @Test
    @DisplayName("DELETE /api/students/{id} should remove student")
    void testDeleteStudent() throws Exception {
        // Given
        doNothing().when(studentService).deleteById(1L);

        // When & Then
        mockMvc.perform(delete("/api/students/1"))
            .andExpect(status().isNoContent());

        verify(studentService, times(1)).deleteById(1L);
    }
}