package com.example.studentapi.model;

import jakarta.validation.constraints.*;
import lombok.Data;

/**
 * Student entity representing a student in the management system.
 * Generated by IBM Bob - Assignment Decoder
 */
@Data
public class Student {

    private Long id;

    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    private String name;

    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    private String email;

    @NotNull(message = "Age is required")
    @Min(value = 18, message = "Age must be at least 18")
    @Max(value = 100, message = "Age must not exceed 100")
    private Integer age;

    // TODO: Add additional fields as needed (e.g., enrollmentDate, major, etc.)
    // TODO: Consider adding @CreatedDate and @LastModifiedDate for auditing
}

/**
 * REST Controller for Student CRUD operations.
 * Generated by IBM Bob - Assignment Decoder
 */
@RestController
@RequestMapping("/api/students")
@Validated
public class StudentController {

    @Autowired
    private StudentService studentService;

    /**
     * Get all students
     * @return List of all students
     */
    @GetMapping
    public ResponseEntity<List<Student>> getAllStudents() {
        // TODO: Implement pagination using @PageableDefault
        return ResponseEntity.ok(studentService.findAll());
    }

    /**
     * Get student by ID
     * @param id Student ID
     * @return Student if found
     */
    @GetMapping("/{id}")
    public ResponseEntity<Student> getStudentById(@PathVariable Long id) {
        // TODO: Handle StudentNotFoundException
        return ResponseEntity.ok(studentService.findById(id));
    }

    /**
     * Create new student
     * @param student Student data
     * @return Created student with HTTP 201
     */
    @PostMapping
    public ResponseEntity<Student> createStudent(@Valid @RequestBody Student student) {
        // TODO: Check for duplicate email before saving
        Student created = studentService.save(student);
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    /**
     * Update existing student
     * @param id Student ID
     * @param student Updated student data
     * @return Updated student
     */
    @PutMapping("/{id}")
    public ResponseEntity<Student> updateStudent(
            @PathVariable Long id,
            @Valid @RequestBody Student student) {
        // TODO: Verify student exists before updating
        student.setId(id);
        return ResponseEntity.ok(studentService.update(student));
    }

    /**
     * Delete student
     * @param id Student ID
     * @return HTTP 204 No Content
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteStudent(@PathVariable Long id) {
        // TODO: Consider soft delete instead of hard delete
        studentService.deleteById(id);
        return ResponseEntity.noContent().build();
    }
}